sudo: false
language: node_js
node_js:
  - '5.4.1'
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.1.1
before_script:
  - gem install sass
  - jspm install
  - bower install
services: mongodb
